### ISSUE TITLE
Create youtube playlist connection in Rock

### ISSUE THREAD

**Issue by conrad-vanl** [Differential/willow-prototype#8]
#### Problem Details

To allow Willow to associate youtube content to the app with personalization, we should create content channels in Rock where each content item can represent a youtube feed or single video.

Here are some potential use cases to consider:

- A campus video playlist for members of a specific campus
- A playlist of video stories for all members
- A single video to get "featured" on the home screen

This issue is in relationship to this basecamp post: https://3.basecamp.com/3926363/buckets/6947926/messages/1920543238

I believe the core of this issue is being able to create a content channel of youtube playlist items from playlists that are defined in content channels in Rock. So what we'd have to do is load a content channel that contains references to youtube playlist ids, then use the youtube API to grab playlist items from those playlist ids.

#### Acceptance Criteria

* [x] There is a featured card on the "grow" tab and "my willow" tab (we need two campaign content channels, I think?)
* [x] A "My Willow Youtube" content channel that allows a Rock user to specify youtube playlists for the my willow tab
* [x] A "Church-wide Youtube" or "Grow Tab Youtube" content channel that allows a Rock user to specify youtube playlists for the grow tab
* [x] Create a "my willow" feed query that grabs content specific to your campus. For MVP, this can be just youtube content from your campus's youtube playlist
* [x] The current "userFeed" query will be the feed query used on the "grow" tab (with a campaign query driving the featured card at the beginning). This should work the same as it does now, just with youtube content mixed in

For reference, here's some screenshots of what I'm currently trying to deliver with this issue:

![image](https://user-images.githubusercontent.com/103927/61299982-be434480-a7a6-11e9-80e2-38711925f1ef.png)

![image](https://user-images.githubusercontent.com/103927/61300174-18440a00-a7a7-11e9-8052-e7b51c798f76.png)

**Comment by conrad-vanl** [comment]
PS...we should either merge [this PR](https://github.com/Differential/willow-prototype/pull/7) or do this work in that PR

**Comment by vinnyjth** [comment]
> There is a featured card on the "grow" tab and "my willow" tab (we need two campaign content channels, I think?)
Solved by creating ContentChannels to hold both the grow featured content item, and the "my willow" featured content item
>  A "My Willow Youtube" content channel that allows a Rock user to specify youtube playlists for the my willow tab
Pulls videos from a `Youtube` Content Channel, I tagged each video with a Campus persona, and then I fetch youtube videos tagged with your current campus persona. 
>  A "Church-wide Youtube" or "Grow Tab Youtube" content channel that allows a Rock user to specify youtube playlists for the grow tab
Right now pulls from your persona feed. Happens to be identical to your MyWIllow feed right now, because Willow doesn't have any personas build.
>  Create a "my willow" feed query that grabs content specific to your campus. For MVP, this can be just youtube content from your campus's youtube playlist
Pulls videos from a `Youtube` Content Channel, I tagged each video with a Campus persona, and then I fetch youtube videos tagged with your current campus persona. 
>  The current "userFeed" query will be the feed query used on the "grow" tab (with a campaign query driving the featured card at the beginning). This should work the same as it does now, just with youtube content mixed in
Uses the persona feed.
